name: Code Check And Test

on:
  push:
    paths:
      - "**.py"
      - "pyproject.toml"
    branches:
      - "*"

jobs:
  Code-Check:
    runs-on: ubuntu-latest
    if: contains(github.server_url, 'github.com')
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip ruff
    - name: Code Check
      run: |
        ruff check
        ruff format --check
  Code-Test:
    env:
      FEISHU_APP_ID: ${{ secrets.FEISHU_APP_ID }}
      FEISHU_APP_SECRET: ${{ secrets.FEISHU_APP_SECRET }}
      FEISHU_PHONE: ${{ secrets.FEISHU_PHONE }}

    runs-on: ubuntu-latest
    if: contains(github.server_url, 'github.com')
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; else pip install .; fi
    - name: Code Test
      run: python -m unittest discover -s tests -p "test_*.py"
